# Generated by Django 4.2.1 on 2023-07-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('kg1', 'Kindergarten 1'), ('kg2', 'Kindergarten 2'), ('nur1', 'Nursery 1'), ('nur2', 'Nursery 2'), ('pr1', 'Primary 1'), ('pr2', 'Primary 2'), ('pr3', 'Primary 3'), ('pr4', 'Primary 4'), ('pr5', 'Primary 5')], max_length=4)),
                ('subjects', models.ManyToManyField(related_name='grades_taught_in', to='main.subject')),
            ],
        ),
    ]
