# Generated by Django 4.2.1 on 2023-07-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_teacherprofile_image_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='bio',
            field=models.TextField(null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='qualifications',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subject_specializations',
            field=models.ManyToManyField(related_name='specialized_teachers', to='main.subject'),
        ),
    ]
