# Generated by Django 4.2.6 on 2023-11-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_termreport_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='images/admin_profiles'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='position',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='images/student_profiles'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='subjects',
            field=models.ManyToManyField(null=True, related_name='offering_students', to='main.subject'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='images/teacher_profiles'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subject_specializations',
            field=models.ManyToManyField(null=True, related_name='specialized_teachers', to='main.subject'),
        ),
    ]
