# Generated by Django 4.2.2 on 2023-11-11 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTermReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(default='Awaiting remark...', max_length=200)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_reports', to='main.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_reports', to='main.studentprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reports', to='main.term')),
            ],
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='term_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.studenttermreport'),
        ),
        migrations.DeleteModel(
            name='TermReport',
        ),
    ]
