# Generated by Django 4.2.1 on 2023-07-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passkey',
            field=models.CharField(editable=False, max_length=13, unique=True),
        ),
    ]
