# Generated by Django 4.2.1 on 2023-07-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_passkey'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'passkey')},
        ),
    ]
