# Generated by Django 4.2.1 on 2023-07-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_educator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('educator', 'Educator')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passkey',
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
    ]
