# Generated by Django 4.2.1 on 2023-07-22 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_dob_user_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(message="Invalid formatting. Here's an example:\n\t'+2348011235813' corresponds to '08011235813'", regex='\\+(234)[789][01]\\d{8}')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passkey',
            field=models.CharField(blank=True, editable=False, max_length=13, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'passkey')},
        ),
    ]
