# Generated by Django 4.2.1 on 2023-07-22 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_unique_together_user_address_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="Invalid formatting. Here's an example:\n\t'+2348011235813' corresponds to '08011235813'", regex='\\+(234)[789][01]\\d{8}')], verbose_name='Phone Number'),
        ),
    ]
